### ISSUE TITLE
Extra debug...

### ISSUE THREAD

**Issue by ranguard** [robrwo/Plack-Middleware-LogHarakiri#2]
Thanks for writing this...

Wouldn't extra debug info ( like request path or something ) be useful... even as a flag of what to dump

Leo

**Comment by robrwo** [comment]
Yes, that would be useful.

I'm thinking a better idea would be to provide a callback to change the log message.

So that by default it would be the current message line (backwards compatability ;) but you can change the format to output whatever information you are interested in.

**Comment by robrwo** [comment]
Fixed in release 0.0200
